#!/usr/bin/python
import sys
import base64

print('\n\n\n')
print("use it like Wordlist_b64_USER_PASS.py usernames.txt passwords.txt output.txt")
print('\n\n\n')

def create(USER,PASS,OUT):
    U=open(USER,"r");
    U_list = U.readlines()
    P=open(PASS,"r");
    P_list = P.readlines()
    file3=open(OUT,"w")

    for x in U_list:
        for y in P_list:
            string = str.strip(x)+':'+str.strip(y)+"\n"
            new = base64.encodestring(string)
            file3.write(new)

    U.close()
    P.close()
    file3.close()

create(sys.argv[1],sys.argv[2],sys.argv[3])
